### ISSUE TITLE
Binary Classifier Weights

### ISSUE THREAD

**Issue by cyq1017** [ttanida/rgrg#10]
Hi,
Thanks for your great contributions.
I wonder if it is possible to share the checkpoint of the best pre-trained model of training stage 2.
Thanks

**Comment by ttanida** [comment]
Hi,

of course, this is the [checkpoint](https://drive.google.com/file/d/1xK7whO-OaWkJnbMuF_AdQNGpWh0UJS0b/view?usp=sharing).

Best,
Tim

**Comment by cyq1017** [comment]
Thank you very much for your prompt reply, it's very useful to me!
