### ISSUE TITLE
train, test, valid csv appear empty

### ISSUE THREAD

**Issue by IQraQasim10** [ttanida/rgrg#17]
Thanks for wonderful contribution.
I am diligently following your provided read.me file. While running `python create_dataset.py` the train, test and validation files are successfully created but appears to be empty. Here is the illustration of my file navigator. 
<img width="159" alt="image" src="https://github.com/ttanida/rgrg/assets/91534850/a1e984be-642f-4729-8dcd-835d451c7e6f">
Here is my path specifications in case you need to help 
<img width="636" alt="image" src="https://github.com/ttanida/rgrg/assets/91534850/01f1df31-a8c0-4d06-a54c-9d6712663103">
Just for reference: I have mistakenly copied physionet.org data twice which appears as main folder name in some paths. So my main folder and sub folder has the data twice. please ignore this. 

Thank you in advance

**Comment by Cckyrie** [comment]
Hello!I have meet the same problem.How did you solve this problem?
