### ISSUE TITLE
Custom ROIs

### ISSUE THREAD

**Issue by FJonske** [ttanida/rgrg#23]
Very cool project!

I have a question regarding Fig. 3 and 4 in the README. How would I go about specifying a custom ROI and generating text only for that ROI? Unless I have missed something, the code in this repo seems to only allow getting entire reports, with ROIs being chosen by the model. The only way to do what I want that I can see right now is pass a custom ROI in at the very start of generate_reports_for_images.py. I'd add it to the generated region proposals in the object detector (or replace all the regular proposals even).

Is there a more straightforward way that I'm missing? If so, please let me know.

**Comment by ttanida** [comment]
Take a look in this [script](https://github.com/ttanida/rgrg/blob/main/src/full_model/evaluate_bbox_variations/evaluate_bbox_variations.py), especially this [line](https://github.com/ttanida/rgrg/blob/eb64933e222e8b18cd78c257c822a349b024c008/src/full_model/evaluate_bbox_variations/evaluate_bbox_variations.py#L128C9-L128C75).

It allows you to generate text for predefined bbox coordinates in an image.

**Comment by FJonske** [comment]
That is exactly what I was looking for, thank you :)
