### ISSUE TITLE
Is there seperate weights for Faster R-CNN + Binary classifiers?

### ISSUE THREAD

**Issue by YatingPan** [ttanida/rgrg#25]
Hi, I want to use the Faster R-CNN and binary classifiers trained on Chest ImaGenome, but didn't find the isolated weights for these components. I extracted the weights for these 2 components from the full model weights, but based on some inference on Chest ImaGenome's test datasets, the binary classifiers' outputs are not so accurate... Are there any isolated weights or evaluation results for this part? Thank you very much!

**Comment by ttanida** [comment]
Hi,

please take a look at this issue for the object detector weights:
https://github.com/ttanida/rgrg/issues/3
and this issue for the object detector + binary classifier weights:
https://github.com/ttanida/rgrg/issues/10

Best,
Tim

Am Mi., 20. März 2024 um 11:02 Uhr schrieb Yating Pan <
***@***.***>:

**Comment by YatingPan** [comment]
Ok Thanks!
