### ISSUE TITLE
Faster R-CNN  pre-trained weights

### ISSUE THREAD

**Issue by nooralahzadeh** [ttanida/rgrg#3]
Hi, 
Thanks for sharing the code.
I wonder if it is possible to share the weights for the object detector (Faster R-CNN ) which is fine-tuned or trained on the Chest ImaGenome Dataset.
Thanks

**Comment by ttanida** [comment]
Hi, of course, these are the object detector weights:

https://drive.google.com/file/d/1JkZax3VUFC3QfgbLNSsTlXJTKBKBWpvF/view?usp=sharing
