### ISSUE TITLE
When performing inference using the full model to generate reports, is it necessary to load the checkpoint file of the object detector?

### ISSUE THREAD

**Issue by jianfeixu95** [ttanida/rgrg#31]
According to the README's Inference section, "To generate reports for a list of images, run python generate_reports_for_images.py. Specify the model checkpoint, the list of image paths, and the path to the txt file with the generated reports in the main function."

In the comments of the “generate_reports_for_images.py” file, it is only mentioned that the checkpoint file path of the full model needs to be specified. However, in line 150 of this file, the “get_model(checkpoint_path)” function references “model = ReportGenerationModel(pretrain_without_lm_model=True)”. In the “__init__” function of the “ReportGenerationModel” Class, when training the full model, it needs to load the object detector checkpoint file ”self.object_detector.load_state_dict(torch.load(path_to_best_object_detector_weights))“

Therefore, I am confused. During inference, besides needing the checkpoint file of the full model, do we also need to load the checkpoint file of the object detector?

**Comment by ttanida** [comment]
No, just specify everything in generate_reports_for_images.py. You don’t have to change anything else. Even if you specified the object detector weights, this line would overwrite the those weights with the full mode weights anyway: https://github.com/ttanida/rgrg/blob/9520b6d7f555d458898c6795e57cc00f7f90182b/src/full_model/generate_reports_for_images.py#L161

You only have to explicitly specify the object detector weights when you go through 3 the training stages. It’s irrelevant for inference.
