### ISSUE TITLE
Some questions about the 'object_detector'

### ISSUE THREAD

**Issue by Liqq1** [ttanida/rgrg#5]
Hi, I am trying to use [the Faster R-CNN pre-trained weights]( https://github.com/ttanida/rgrg/issues/3) you provided to detect the regions in X-ray image, but the results were very unsatisfactory and did not reach the IOU described in the appendix of the paper. Could you help me check what's wrong?

The code is：
```
from src.object_detector.object_detector import ObjectDetector

#image [1,1,512,512]
image = Image.open('  ').convert("L")
img= np.array(image)
img = torch.tensor(cv2.resize(img,dsize=(512, 512)))
img = img.unsqueeze(0)
img = img.unsqueeze(1)

#detector
object_detector = ObjectDetector(return_feature_vectors=False)
path_to_best_object_detector_weights = " "
object_detector.load_state_dict(torch.load(path_to_best_object_detector_weights))
_, detections, class_detected = object_detector(img)
```
The result is：
![dbda836652d2c2e9a59f80c375980519](https://github.com/ttanida/rgrg/assets/54054113/25ce89cb-99f5-456d-aaa6-d9bebde5b596)
Should all 'class_detected' be True? And some bboxes are lines or points, which looks incorrect.

**Comment by ttanida** [comment]
Hi,

Thank you for reaching out. The problem appears to be that you are pre-processing the image in a different way than what we did in our pipeline. Therefore, the object detector sees something that it hasn't seen during training and thus outputs unsatisfactory results.

Please take a look at [this post](https://github.com/ttanida/rgrg/issues/1#issuecomment-1500113523), where I list the image transformations we applied during our work.

Could you try again with the code below? This is how we pre-processed the images in our pipeline:


```
import albumentations as A
from albumentations.pytorch import ToTensorV2
import cv2

IMAGE_INPUT_SIZE = 512
mean = 0.471  # see get_transforms in src/object_detector/training_script_object_detector.py
std = 0.302

# cv2.imread by default loads an image with 3 channels
# since we have grayscale images, we only have 1 channel and thus use cv2.IMREAD_UNCHANGED to read in the 1 channel
image = cv2.imread(image_path, cv2.IMREAD_UNCHANGED)  # shape (3056, 2544)

val_test_transforms = A.Compose(
    [
        A.LongestMaxSize(max_size=IMAGE_INPUT_SIZE, interpolation=cv2.INTER_AREA),
        A.PadIfNeeded(min_height=IMAGE_INPUT_SIZE, min_width=IMAGE_INPUT_SIZE, border_mode=cv2.BORDER_CONSTANT),
        A.Normalize(mean=mean, std=std),
        ToTensorV2(),
    ]
)

transform = val_test_transforms(image=image)
image_transformed = transform["image"]  # shape (1, 512, 512)
image_transformed_batch = image_transformed.unsqueeze(0)  # shape (1, 1, 512, 512)

object_detector = ObjectDetector(return_feature_vectors=False)
object_detector.load_state_dict(torch.load(path_to_best_object_detector_weights))

object_detector.eval()

with torch.no_grad():
    _, detections, class_detected = object_detector(image_transformed_batch)
```

**Comment by Liqq1** [comment]
Thanks for your guidance, now the result looks much more reasonable
![dddd6721045ddc8d3fa2293ed47bbc34](https://github.com/ttanida/rgrg/assets/54054113/4391c1f9-3c23-4624-b49d-49c6b07fcc6c)
