### ISSUE TITLE
MIMIC-CXR test results

### ISSUE THREAD

**Issue by wjhou** [ttanida/rgrg#6]
Hi, 

Thanks for your great contributions.
Is that possible that you could provide the test results of the best checkpoint, as we want to do some evaluation compared with the RGRG model?

Thanks

**Comment by ttanida** [comment]
Hello,

all results published in our paper are test results of the best checkpoint.

Best,
Tim

**Comment by wjhou** [comment]
Hi,
Thanks for your prompt response. Is it possible to send the generated reports of all test images? Because we want to compare more about entity evaluation with the RGRG model.

Best,
Ethan

From: Tim Tanida ***@***.***>
Date: Monday, June 12, 2023 at 15:00
To: ttanida/rgrg ***@***.***>
Cc: Ethan, Wenjun Hou ***@***.***>, Author ***@***.***>
Subject: Re: [ttanida/rgrg] MIMIC-CXR test results (Issue #6)

Hello,

all results published in our paper are test results of the best checkpoint.
Could you elaborate on what you mean?

Best,
Tim

**Comment by ttanida** [comment]
Hi Ethan,

I would have to first check with the authors of MIMIC-CXR if we can legally share the generated reports.
I will get back to you once I have the answer.

Best,
Tim

**Comment by ttanida** [comment]
Yesterday, I reached out to the authors via email.

While awaiting their response, there's an alternate way should you urgently require the generated reports. First, create the test set csv files by running 'create_dataset.py.' Following this, execute 'test_set_evaluation.py' which will produce a 'generated_reports.txt.' This file will comprise both the generated and reference reports.

Bear in mind that due to the substantial size of the test set (32,711 images), the evaluation process is time-consuming. Our evaluation run took approximately three days utilizing a single Nvidia A40. Although somewhat laborious, this method provides a viable alternative for procuring the generated reports.

**Comment by wjhou** [comment]
Thank you for your suggestions. We will try it later.

**Comment by ttanida** [comment]
I've received a response from the authors. They recommended that I publish the reports as a credentialed resource on PhysioNet. Doing so would enable the sharing of the reports under the same access restrictions as those applicable to MIMIC-CXR.

However, this approach involves a comprehensive data preparation stage followed by a rigorous peer review process (which would take a considerable amount of time). After considering these requirements, I believe generating the reports directly would be a more time-efficient solution.

Nevertheless, should there be increased demand for the generated reports, I am open to considering the publication route on PhysioNet to facilitate broader access.

**Comment by DavidYanAnDe** [comment]
> Yesterday, I reached out to the authors via email.
> 
> While awaiting their response, there's an alternate way should you urgently require the generated reports. First, create the test set csv files by running 'create_dataset.py.' Following this, execute 'test_set_evaluation.py' which will produce a 'generated_reports.txt.' This file will comprise both the generated and reference reports.
> 
> Bear in mind that due to the substantial size of the test set (32,711 images), the evaluation process is time-consuming. Our evaluation run took approximately three days utilizing a single Nvidia A40. Although somewhat laborious, this method provides a viable alternative for procuring the generated reports.

After 'create_dataset.py.' I run 'test_set_evaluation.py' but get:
