### ISSUE TITLE
Data statistic

### ISSUE THREAD

**Issue by zhaozh10** [ttanida/rgrg#7]
hi Tim,  I mentioned that not all samples in the ChestImaGenome dataset have ''finding'' sections, so when implementing ``src/dataset/creation_dataset.py``, I got 15658/31271/1440 samples for val/test/test-2.csv, respectively. These numbers were not mentioned in the paper, so I hope to confirm if they align with your implementation.

**Comment by ttanida** [comment]
Hi,

these numbers are correct.

If you take a look at section 4.1 of the main paper, we mention that we use 32,711 test images (i.e. 31,271 + 1,440) with corresponding reports after discarding all reference reports with empty "findings" sections.

**Comment by zhaozh10** [comment]
Gosh! Thank you so much! I overlooked this detail in the paper

**Comment by DavidYanAnDe** [comment]
hello, but after I run the src/dataset/creation_dataset.py, I get train/valid/test/test2 for 166105/15626/31179/1431 line in each .csv files. Is my dataset get something wrong?

**Comment by zhaozh10** [comment]
> hello, but after I run the src/dataset/creation_dataset.py, I get train/valid/test/test2 for 166105/15626/31179/1431 line in each .csv files. Is my dataset get something wrong?

Yeah, there may be something wrong, the data splits I got strictly follow the description in the paper.

**Comment by ttanida** [comment]
Hi @DavidYanAnDe,

these are the number of rows you should get for the csv files generated by create_dataset.py:

train: 166,504
valid: 15,658
test: 31,271
test-2: 1,440

It seems like you are missing some rows, e.g. 399 rows in train.csv, 32 rows in valid.csv etc.

I suspect the cause of these missing rows is that you are probably missing some images in MIMIC-CXR-JPG.
If you take a look at this [line](https://github.com/ttanida/rgrg/blob/eb64933e222e8b18cd78c257c822a349b024c008/src/dataset/create_dataset.py#L406) in create_dataset.py, you can see that missing images are skipped in the script, i.e. no row is created for missing images.

After running create_dataset.py, a log file called **log_file_dataset_creation.txt** should have been created, in which you can see if there were any missing images (and also missing reports in case for the valid and test csv files).

I would recommend you to write a script that checks if all image paths specified in the train, valid, test csv files in the directory chest-imagenome-dataset-1.0.0/silver_dataset/splits exist in your corresponding MIMIC-CXR-JPG directory. For this, you would have to loop over the "path" column in the csv files, replace .dcm with .jpg in the paths, and check with os.path.exists if the path exists in your MIMIC-CXR-JPG directory.

**Comment by DavidYanAnDe** [comment]
@ttanida , follow your suggestion, I find that I loss some image in the log file. Could you please share me your correct log_file_dataset_creation.txt file so that I can confirm? thank you very much.

**Comment by ttanida** [comment]
There should be exactly 0 missing images and 0 missing reports in the final created log txt file. I just saw in the code that if there are any missing images, then the file paths of these images will also be logged, so you should see exactly which images are missing.

**Comment by DavidYanAnDe** [comment]
> 最终创建的日志 txt 文件中应该正好有 0 个缺失图像和 0 个缺失报告。我刚刚在代码中看到，如果有任何丢失的图像，那么这些图像的文件路径也会被记录，所以你应该准确地看到哪些图像丢失了。

Thanks, the image with ignored_or_avoided and faulty_bboxes don't need to care about it, right?

**Comment by ttanida** [comment]
Yes, there will be some ignored and avoided images, as well as faulty bboxes, but they are no problem as they are handled already.
